### ISSUE TITLE
entrevista a un desarrollador de software 

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-jdgras#1]
[Entrevista (3).pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-jdgras/files/12581129/Entrevista.3.pdf)

**Comment by ka194** [comment]
19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
